---
- name: provision ec2 instances based on the environment
  hosts: local
  connection: local
  gather_facts: False

  vars_files:
    - vars/environment.yaml
    - vars/keys-aws.yaml

  tasks:

    - name: create instance admin


      ec2:
        ec2_access_key: "{{ aws_access_key }}"
        ec2_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ keypair1 }}"
        region: "{{ aws_region }}"
        instance_type: t2.micro
        image: "{{ image_id }}"
        wait: yes
        group: ['ssh','outbound']
        instance_tags: 
          Name: admin-instance
        exact_count: 1
        count_tag: 
          Name: admin-instance
        vpc_subnet_id: "{{ subnet_public }}"
        assign_public_ip: yes

    - name: create instance web

      ec2:
        ec2_access_key: "{{ aws_access_key }}"
        ec2_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ keypair2 }}"
        region: "{{ aws_region }}"
        instance_type: t2.micro
        image: "{{ image_id }}"
        wait: yes
        group: ['web','ssh']
        instance_tags: 
          Name: web-server
        exact_count: 1
        count_tag: 
          Name: web-server
        vpc_subnet_id: "{{ subnet_public }}"
        assign_public_ip: yes

    - name: create instance app

      ec2:
        ec2_access_key: "{{ aws_access_key }}"
        ec2_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ keypair3 }}"
        region: "{{ aws_region }}"
        instance_type: t2.micro
        image: "{{ image_id }}"
        wait: yes
        group: ['ssh']
        instance_tags: 
          Name: app-server
        exact_count: 1
        count_tag: 
          Name: app-server
        vpc_subnet_id: "{{ subnet_private }}"

