---
- name: Create VPC
  hosts: local
  connection: local
  gather_facts: False

  vars_files:
    - vars/environment.yaml
    - vars/keys-aws.yaml


  tasks:

    - name: internet gateway
      ec2_vpc_igw:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: present
      register: igw
