---
- name: create keypair
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/environment.yaml
    - vars/keys-aws.yaml

  tasks:

    - name: create keypair admin
      ec2_key:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        name: admin-instance
      register: keypair


    - name: create keypair web
      ec2_key:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        name: web-instance
      register: keypair


    - name: create keypair app
      ec2_key:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        name: app-server
      register: keypair


    - name: Write the key to a file
      copy:
        dest: "{{ dest1 }}"
        content: "{{ keypair.key }}"
        mode: 0600
      when: keypair.changed


    - name: Write the key to a file
      copy:
        dest: "{{ dest2 }}"
        content: "{{ keypair.key }}"
        mode: 0600
      when: keypair.changed


    - name: Write the key to a file
      copy:
        dest: "{{ dest3 }}"
        content: "{{ keypair.key }}"
        mode: 0600
      when: keypair.changed