---
# region, zone, image_id, vpc_id, keypair

aws_region: us-west-2
aws_zonea: us-west-2a
aws_zoneb: us-west-2b
vpc_id: vpc-0fd59fdc86ee0ce5e
subnet_public: subnet-06b51e157ee35f4ed
subnet_private: subnet-0cb468309b08ca2c7
internet_gateway: igw-0275659b9cb013c77
image_id: ami-03d5c68bab01f3496


# Keypair

dest1: /home/moisesyanes/Documents/aws-keypairs/admin-instance.pem
dest2: /home/moisesyanes/Documents/aws-keypairs/web-instance.pem
dest3: /home/moisesyanes/Documents/aws-keypairs/app-server.pem
keypair1: admin-instance
keypair2: web-instance
keypair3: app-server


# security groups to be created
security_groups:

  - name: ssh
    desc: security group for ssh
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

  - name: web
    desc: security group for the web server 
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0


  - name: outbound
    desc: segurity group for outbound
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0

  
# Instances to launch be launched.

ec2_instances:

  - instance_type: t2.micro
    image: "{{ image_id }}"
    keypair: "{{ keypair1 }}"
    subnet: "{{ subnet_public }}"
    assign_public_ip: yes
    group: ['ssh','outbound']
    instance_tags: 
        Name: admin-instance
    exact_count: 1
    count_tag: 
        Name: admin-instance

  - instance_type: t2.micro
    image: "{{ image_id }}"
    keypair: "{{ keypair2 }}"
    subnet: "{{ subnet_public }}"
    assign_public_ip: yes
    group: ['web','ssh'] 
    instance_tags: 
        Name: web-server
    exact_count: 1 
    count_tag: 
        Name: web-server

  - instance_type: t2.micro
    image: "{{ image_id }}"
    keypair: "{{ keypair3 }}"
    subnet: "{{ subnet_private }}"
    group: ['ssh'] 
    instance_tags: 
        Name: app-server
    exact_count: 1
    count_tag: 
        Name: app-server
